/*
 Copyright (c) 2014, Pixel & Tonic, Inc.
 @license   http://buildwithcraft.com/license Craft License Agreement
 @see       http://buildwithcraft.com
 @package   craft.app.resources
*/
(function(b){Craft.RichTextInput=Garnish.Base.extend({id:null,sectionSources:null,elementLocale:null,redactorConfig:null,$textarea:null,redactor:null,init:function(a,e,c,d,f){this.id=a;this.sectionSources=e;this.elementLocale=c;this.redactorConfig=d;this.redactorConfig.lang=f;this.redactorConfig.direction=Craft.orientation;var g=this,h=d.initCallback;this.redactorConfig.initCallback=function(a,c){g.redactor=this;g.onRedactorInit();return b.isFunction(h)?h.call(this,a,c):c};this.$textarea=b("#"+this.id);
this.initRedactor();"undefined"!=typeof Craft.livePreview&&(Craft.livePreview.on("beforeEnter beforeExit",b.proxy(function(){this.redactor.destroy()},this)),Craft.livePreview.on("enter slideOut",b.proxy(function(){this.initRedactor()},this)))},initRedactor:function(){this.$textarea.redactor(this.redactorConfig);this.redactor=this.$textarea.data("redactor")},onRedactorInit:function(){this.replaceRedactorButton("image",Craft.t("Insert image"),null,{from_web:{title:Craft.t("Insert URL"),func:"imageShow"},
from_assets:{title:Craft.t("Choose image"),callback:b.proxy(function(){this.redactor.selectionSave();"undefined"==typeof this.assetSelectionModal?this.assetSelectionModal=Craft.createElementSelectorModal("Asset",{storageKey:"RichTextFieldType.ChooseImage",multiSelect:!0,criteria:{locale:this.elementLocale,kind:"image"},onSelect:b.proxy(function(a,e){if(a.length){this.redactor.selectionRestore();for(var c=0;c<a.length;c++){var d=a[c],d=d.url+"#asset:"+d.id;e&&(d+=":"+e);this.redactor.insertNode(b('<img src="'+
d+'" />')[0]);this.redactor.sync()}this.redactor.observeImages();this.redactor.dropdownHideAll()}},this),closeOtherModals:!1,canSelectImageTransforms:!0}):this.assetSelectionModal.show()},this)}});this.replaceRedactorButton("link",Craft.t("Link"),null,{link_entry:{title:Craft.t("Link to an entry"),callback:b.proxy(function(){this.redactor.selectionSave();"undefined"==typeof this.entrySelectionModal?this.entrySelectionModal=Craft.createElementSelectorModal("Entry",{storageKey:"RichTextFieldType.LinkToEntry",
sources:this.sectionSources,criteria:{locale:this.elementLocale},onSelect:b.proxy(function(a){if(a.length){this.redactor.selectionRestore();a=a[0];var e=a.url+"#entry:"+a.id,c=this.redactor.getSelectionText();this.redactor.insertNode(b('<a href="'+e+'">'+(0<c.length?c:a.label)+"</a>")[0]);this.redactor.sync()}this.redactor.dropdownHideAll()},this),closeOtherModals:!1}):this.entrySelectionModal.show()},this)},link_asset:{title:Craft.t("Link to an asset"),callback:b.proxy(function(){this.redactor.selectionSave();
"undefined"==typeof this.assetLinkSelectionModal?this.assetLinkSelectionModal=Craft.createElementSelectorModal("Asset",{storageKey:"RichTextFieldType.LinkToAsset",criteria:{locale:this.elementLocale},onSelect:b.proxy(function(a){if(a.length){this.redactor.selectionRestore();a=a[0];var e=a.url+"#asset:"+a.id,c=this.redactor.getSelectionText();this.redactor.insertNode(b('<a href="'+e+'">'+(0<c.length?c:a.label)+"</a>")[0]);this.redactor.sync()}this.redactor.dropdownHideAll()},this),closeOtherModals:!1,
canSelectImageTransforms:!0}):this.assetLinkSelectionModal.show()},this)},link:{title:Craft.t("Insert link"),func:"linkShow"},unlink:{title:Craft.t("Unlink"),exec:"unlink"}});if("undefined"!=typeof this.redactor.fullscreen&&"function"==typeof this.redactor.toggleFullscreen)Craft.cp.on("beforeSaveShortcut",b.proxy(function(){this.redactor.fullscreen&&this.redactor.toggleFullscreen()},this))},replaceRedactorButton:function(a,b,c,d){if(this.redactor.buttonGet(a).length){var f=a+"_placeholder";this.redactor.buttonAddAfter(a,
f);this.redactor.buttonRemove(a);this.redactor.buttonAddAfter(f,a,b,c,d);this.redactor.buttonRemove(f)}}})})(jQuery);

//# sourceMappingURL=RichTextInput.min.map
